set -g mouse on

# Plugin manager
set -g @plugin 'tmux-plugins/tpm'

# Save and restore tmux sessions
set -g @plugin 'tmux-plugins/tmux-resurrect'

# Auto save and restore
set -g @plugin 'tmux-plugins/tmux-continuum'

# automatically restore on tmux start
set -g @continuum-restore 'on'

run '~/.tmux/plugins/tpm/tpm'
